# Loaded by CMAKE_PROJECT_nemo_speech_INCLUDE. Run after upstream defines targets.
function(hearth_configure_nemo)
  target_sources(nemo_speech_asr_c PRIVATE "${HEARTH_CPP}/speech/backends/nemotron_backend.cpp")
  set_target_properties(nemo_speech_asr_c PROPERTIES OUTPUT_NAME hearth_nemotron)
  set_property(TARGET nemo_speech_asr_c PROPERTY SOVERSION)
  set_property(TARGET nemo_speech_asr_c PROPERTY VERSION)
  if(ANDROID)
    target_link_libraries(nemo_speech_asr_c PRIVATE log)
    target_link_options(nemo_speech_asr_c PRIVATE "-Wl,-z,max-page-size=16384" "-Wl,--exclude-libs,ALL")
  elseif(APPLE)
    target_link_options(nemo_speech_asr_c PRIVATE "-Wl,-exported_symbol,_hearth_speech_backend_v1")
  endif()
endfunction()
cmake_language(DEFER CALL hearth_configure_nemo)
