cmake_minimum_required(VERSION 3.26)
project(hearth_qwen LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
foreach(option ENABLE_PYTHON ENABLE_TESTS ENABLE_PORTAUDIO ENABLE_JNI ENABLE_WEBSOCKET ENABLE_GPU ENABLE_BINARY ENABLE_TTS ENABLE_SPEAKER_DIARIZATION BUILD_C_API_EXAMPLES)
  set(SHERPA_ONNX_${option} OFF CACHE BOOL "" FORCE)
endforeach()
set(SHERPA_ONNX_USE_PRE_INSTALLED_ONNXRUNTIME_IF_AVAILABLE OFF CACHE BOOL "" FORCE)
add_compile_definitions(HEARTH_SPEECH_CPU_ONLY=1)
add_subdirectory("${SHERPA_SOURCE}" sherpa)
add_library(hearth_qwen SHARED "${HEARTH_CPP}/speech/backends/qwen_backend.cpp")
target_include_directories(hearth_qwen PRIVATE "${SHERPA_SOURCE}")
target_link_libraries(hearth_qwen PRIVATE sherpa-onnx-c-api)
if(ANDROID)
  target_link_libraries(hearth_qwen PRIVATE log android)
  target_link_options(hearth_qwen PRIVATE "-Wl,-z,max-page-size=16384" "-Wl,--exclude-libs,ALL"
    "-Wl,--version-script=${HEARTH_CPP}/speech/backends/qwen_exports.map")
elseif(APPLE)
  target_link_options(hearth_qwen PRIVATE "-Wl,-exported_symbol,_hearth_speech_backend_v1" "-Wl,-exported_symbol,_hearth_moonshine_backend_v1")
endif()
